---
driver_plugin: vagrant

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
    require_chef_omnibus: "11.4.4"

suites:
- name: default
  run_list:
  - "recipe[chef-solo-search]"
  - "recipe[sentry_test::default]"
  - "recipe[minitest-handler]"

- name: encrypted_databag
  run_list:
  - "recipe[chef-solo-search]"
  - "recipe[sentry_test::encrypted_data_bag]"
  - "recipe[minitest-handler]"
  attributes:
    sentry:
      data_bag_item: "sentry_encrypted"
      use_encrypted_data_bag: true
  encrypted_data_bag_secret_key_path: "test/data_bag_secret"
