---
driver:
  name: docker
  driver_config:
    use_sudo: false

provisioner:
  name: chef_solo
  require_chef_omnibus: true

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
    - "recipe[chef-solo-search]"
    - "recipe[sentry_test::default]"
    - "recipe[minitest-handler]"

  - name: encrypted_databag
    run_list:
    - "recipe[chef-solo-search]"
    - "recipe[sentry_test::encrypted_data_bag]"
    - "recipe[minitest-handler]"
    attributes:
      sentry:
        data_bag_item: "sentry_encrypted"
        use_encrypted_data_bag: true
    encrypted_data_bag_secret_key_path: "test/data_bag_secret"
